name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  SOLANA_VERSION: v1.9.14
  ANCHOR_VERSION: v0.23.0
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mrgnlabs/solana-dev:$(date +%s) --build-arg SOLANA_VERSION=$SOLANA_VERSION --build_arg ANCHOR_VERSION=$ANCHOR_VERSION
